# Generated by Django 5.1.5 on 2025-01-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linie',
            fields=[
                ('id_lini', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('ilosc_graczy', models.IntegerField()),
                ('sr_czas_gry', models.IntegerField()),
                ('opis_trybu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obrazenia',
            fields=[
                ('id_obr', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pochodzenie',
            fields=[
                ('id_poch', models.AutoField(primary_key=True, serialize=False)),
                ('miejsce_urodzenia', models.CharField(max_length=100)),
                ('frakcja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ranga',
            fields=[
                ('nazwa_rangi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ilosc_graczy', models.IntegerField(default=0)),
                ('procent_graczy', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RolaPostaci',
            fields=[
                ('id_r', models.AutoField(primary_key=True, serialize=False)),
                ('naz_roli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Runy',
            fields=[
                ('id_run', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('dzialanie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statystyki',
            fields=[
                ('id_stat', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zasoby',
            fields=[
                ('id_zas', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postac',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('rasa', models.CharField(max_length=100)),
                ('wiek', models.IntegerField()),
                ('data_wydania', models.DateField()),
                ('id_lini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.linie')),
                ('id_obr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.obrazenia')),
                ('id_poch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.pochodzenie')),
                ('id_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.rolapostaci')),
                ('id_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.runy')),
            ],
        ),
        migrations.CreateModel(
            name='StatystykiPostaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.FloatField()),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.postac')),
                ('id_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.statystyki')),
            ],
        ),
        migrations.CreateModel(
            name='Trudnosc',
            fields=[
                ('koszt_be', models.IntegerField(primary_key=True, serialize=False)),
                ('stopien_trudnosci', models.CharField(max_length=100)),
                ('nazwa_rangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.ranga')),
            ],
        ),
        migrations.AddField(
            model_name='postac',
            name='koszt_be',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.trudnosc'),
        ),
        migrations.CreateModel(
            name='UmiejetnosciPostaci',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('przycisk', models.CharField(max_length=50)),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.postac')),
            ],
        ),
        migrations.CreateModel(
            name='Umiejetnosci',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('id_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.umiejetnoscipostaci')),
            ],
        ),
        migrations.CreateModel(
            name='Wskaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winrate', models.FloatField()),
                ('banrate', models.FloatField()),
                ('pickrate', models.FloatField()),
                ('tier', models.CharField(max_length=50)),
                ('id_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.postac')),
            ],
        ),
        migrations.AddField(
            model_name='postac',
            name='id_zas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NexusApp.zasoby'),
        ),
    ]
